In [1]:
#load libraries
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("../data/output2.csv", sep=";", index_col=0)

In [3]:
df.shape

(1771817, 23)

In [4]:
# drop "categories" column
df = df.drop(columns=["categories"])

In [7]:
print(df.columns.tolist())

['Employment_Types', 'Expiry_Date', 'Posted_On_Behalf', 'Job_Post_ID', 'New_Post_Date', 'Orig_Post_Date', 'Repost_Count', 'Total_Applications', 'Total_Views', 'Min_Yrs_Experience', 'Vacancies', 'Occupation_ID', 'Position_Level', 'Company_Name', 'Salary_Max', 'Salary_Min', 'Salary_Type', 'Status_ID', 'Job_Status', 'title', 'Avg_Salary', 'Category']

In [6]:
# rename columns name:
df = df.rename(columns={"employmentTypes": "Employment_Types",
                        "metadata_expiryDate": "Expiry_Date",
                        "metadata_isPostedOnBehalf" : "Posted_On_Behalf",
                        "metadata_jobPostId": "Job_Post_ID",
                        "metadata_newPostingDate": "New_Post_Date",  
                        "metadata_originalPostingDate": "Orig_Post_Date",
                        "metadata_repostCount": "Repost_Count",
                        "metadata_totalNumberJobApplication" : "Total_Applications",                     
                        "metadata_totalNumberOfView": "Total_Views",
                        "minimumYearsExperience": "Min_Yrs_Experience",
                        "numberOfVacancies": "Vacancies",
                        "occupationId": "Occupation_ID",
                        "positionLevels": "Position_Level",
                        "postedCompany_name": "Company_Name",
                        "salary_maximum" : "Salary_Max",
                        "salary_minimum" : "Salary_Min",
                        "salary_type": "Salary_Type",
                        "status_id": "Status_ID",
                        "status_jobStatus": "Job_Status",
                        "Title": "Job_Title",
                        "average_salary": "Avg_Salary",
                        "category_single": "Category",
                     })

In [ ]:
 # Show all columns
pd.set_option('display.max_columns', None) 
df.head(10)

,Employment_Types,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Occupation_ID,Position_Level,Company_Name,Salary_Max,Salary_Min,Salary_Type,Status_ID,Job_Status,title,Avg_Salary,Category
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Environment / Health
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Manufacturing
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Sciences / Laboratory / R&D
1,Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,2,NaN,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,Information Technology
2,Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,1,NaN,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0,Repair and Maintenance
3,Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,1,NaN,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0,Information Technology
4,Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,3,NaN,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,Monthly,0,Closed,Sales / Admin Cordinator,2900.0,Admin / Secretarial
5,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,NaN,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,Monthly,0,Closed,Software Support Engineer,5000.0,Consulting
5,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,NaN,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,Monthly,0,Closed,Software Support Engineer,5000.0,Information Technology
5,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,NaN,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,Monthly,0,Closed,Software Support Engineer,5000.0,Professional Services

In [8]:
# save the cleaned data to a new CSV file
df.to_csv("../data/cleaned_output3.csv", sep=";", index=False)

In [9]:
# read the CSV file back into a dataframe, you can use the following code:
df_test_output = pd.read_csv("../data/cleaned_output3.csv", sep=";", index_col=0)

In [10]:
# Display the first 10 rows of the dataframe
df.head(10)

,Employment_Types,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Occupation_ID,Position_Level,Company_Name,Salary_Max,Salary_Min,Salary_Type,Status_ID,Job_Status,title,Avg_Salary,Category
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Environment / Health
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Manufacturing
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Sciences / Laboratory / R&D
1,Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,2,NaN,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,Information Technology
2,Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,1,NaN,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0,Repair and Maintenance
3,Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,1,NaN,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0,Information Technology
4,Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,3,NaN,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,Monthly,0,Closed,Sales / Admin Cordinator,2900.0,Admin / Secretarial
5,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,NaN,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,Monthly,0,Closed,Software Support Engineer,5000.0,Consulting
5,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,NaN,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,Monthly,0,Closed,Software Support Engineer,5000.0,Information Technology
5,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,NaN,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,Monthly,0,Closed,Software Support Engineer,5000.0,Professional Services