In [3]:
# load libraries
import pandas as pd
import numpy as np

In [16]:
# # load data
# df = pd.read_csv("../output4.csv", sep=";", index_col=0)
df=pd.read_csv("../output4.csv", sep=";")

In [17]:
# view the data
df

,Employment_Types,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Position_Level,Company_Name,Salary_Max,Salary_Min,Status_ID,Job_Status,Job_Title,Avg_Salary,Category,Job_Group
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Environment / Health,Other
1,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Manufacturing,Other
2,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Sciences / Laboratory / R&D,Other
3,Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,2,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,Information Technology,Software Engineer
4,Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,1,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,0,Closed,Senior Technician,4200.0,Repair and Maintenance,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767824,Permanent,2024-04-21,False,RANDOM_JOB_20251115011349636339_9,2023-11-18,2023-10-28,2,632,3920,5,902,Non-executive,THALES DIS (SINGAPORE) PTE. LTD.,14420727,164428,0,Re-open,sales and operations manager,7292577.5,Admin / Secretarial,IT Manager
1767825,Permanent,2024-04-21,False,RANDOM_JOB_20251115011349636339_9,2023-11-18,2023-10-28,2,632,3920,5,902,Non-executive,THALES DIS (SINGAPORE) PTE. LTD.,14420727,164428,0,Re-open,sales and operations manager,7292577.5,Customer Service,IT Manager
1767826,Permanent,2024-04-21,False,RANDOM_JOB_20251115011349636339_9,2023-11-18,2023-10-28,2,632,3920,5,902,Non-executive,THALES DIS (SINGAPORE) PTE. LTD.,14420727,164428,0,Re-open,sales and operations manager,7292577.5,Hospitality,IT Manager
1767827,Permanent,2024-04-21,False,RANDOM_JOB_20251115011349636339_9,2023-11-18,2023-10-28,2,632,3920,5,902,Non-executive,THALES DIS (SINGAPORE) PTE. LTD.,14420727,164428,0,Re-open,sales and operations manager,7292577.5,Medical / Therapy Services,IT Manager
1767828,Permanent,2024-04-21,False,RANDOM_JOB_20251115011349636339_9,2023-11-18,2023-10-28,2,632,3920,5,902,Non-executive,THALES DIS (SINGAPORE) PTE. LTD.,14420727,164428,0,Re-open,sales and operations manager,7292577.5,Sales / Retail,IT Manager

In [18]:

df.shape

(1767829, 21)

In [19]:
 # Show all columns
pd.set_option('display.max_columns', None) 
df.head(10)

,Employment_Types,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Position_Level,Company_Name,Salary_Max,Salary_Min,Status_ID,Job_Status,Job_Title,Avg_Salary,Category,Job_Group
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Environment / Health,Other
1,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Manufacturing,Other
2,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Sciences / Laboratory / R&D,Other
3,Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,2,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,Information Technology,Software Engineer
4,Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,1,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,0,Closed,Senior Technician,4200.0,Repair and Maintenance,Other
5,Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,1,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0,Information Technology,Software Engineer
6,Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,3,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,0,Closed,Sales / Admin Cordinator,2900.0,Admin / Secretarial,Other
7,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,0,Closed,Software Support Engineer,5000.0,Consulting,Technical Support
8,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,0,Closed,Software Support Engineer,5000.0,Information Technology,Technical Support
9,Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,0,Closed,Software Support Engineer,5000.0,Professional Services,Technical Support

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1767829 entries, 0 to 1767828
Data columns (total 21 columns):
 #   Column              Dtype
---  ------              -----
 0   Employment_Types    object
 1   Expiry_Date         object
 2   Posted_On_Behalf    bool
 3   Job_Post_ID         object
 4   New_Post_Date       object
 5   Orig_Post_Date      object
 6   Repost_Count        int64
 7   Total_Applications  int64
 8   Total_Views         int64
 9   Min_Yrs_Experience  int64
 10  Vacancies           int64
 11  Position_Level      object
 12  Company_Name        object
 13  Salary_Max          int64
 14  Salary_Min          int64
 15  Status_ID           int64
 16  Job_Status          object
 17  Job_Title           object
 18  Avg_Salary          float64
 19  Category            object
 20  Job_Group           object
dtypes: bool(1), float64(1), int64(8), object(11)
memory usage: 271.4+ MB

In [21]:
# describe the text and string data
df.describe(include=['object'])

,Employment_Types,Expiry_Date,Job_Post_ID,New_Post_Date,Orig_Post_Date,Position_Level,Company_Name,Job_Status,Job_Title,Category,Job_Group
count,1767829,1767829,1767829,1767829,1767829,1767829,1767829,1767829,1767829,1767829,1767829
unique,8,453,1044597,431,603,9,53151,3,377084,43,20
top,Permanent,2023-07-05,RANDOM_JOB_20251115011349636339_9,2023-06-09,2023-07-14,Executive,RECRUITPEDIA PTE. LTD.,Open,SUPERVISOR,Information Technology,Other
freq,854349,7398,5,7650,6987,426975,106391,1529512,9182,140866,1546153

In [22]:
# drop column "Salary_Type" as it has only one unique value
df.drop(columns=['Salary_Type'], inplace=True)

KeyError: "['Salary_Type'] not found in axis"

In [23]:
# view the final dataframe and check the data types and count of non-null values
df.describe(include="all").round(1)

,Employment_Types,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Position_Level,Company_Name,Salary_Max,Salary_Min,Status_ID,Job_Status,Job_Title,Avg_Salary,Category,Job_Group
count,1767829,1767829,1767829,1767829,1767829,1767829,1767829.0,1767829.0,1767829.0,1767829.0,1767829.0,1767829,1767829,1767829.0,1767829.0,1767829.0,1767829,1767829,1767829.0,1767829,1767829
unique,8,453,2,1044597,431,603,NaN,NaN,NaN,NaN,NaN,9,53151,NaN,NaN,NaN,3,377084,NaN,43,20
top,Permanent,2023-07-05,False,RANDOM_JOB_20251115011349636339_9,2023-06-09,2023-07-14,NaN,NaN,NaN,NaN,NaN,Executive,RECRUITPEDIA PTE. LTD.,NaN,NaN,NaN,Open,SUPERVISOR,NaN,Information Technology,Other
freq,854349,7398,1679330,5,7650,6987,NaN,NaN,NaN,NaN,NaN,426975,106391,NaN,NaN,NaN,1529512,9182,NaN,140866,1546153
mean,NaN,NaN,NaN,NaN,NaN,NaN,0.1,2.1,26.2,2.6,2.8,NaN,NaN,5762.8,3708.5,0.0,NaN,NaN,4735.6,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,0.3,10.9,82.7,2.5,12.2,NaN,NaN,71928.8,3121.8,0.0,NaN,NaN,36432.7,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,NaN,NaN,1.0,1.0,0.0,NaN,NaN,1.0,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,1.0,1.0,NaN,NaN,3200.0,2500.0,0.0,NaN,NaN,2855.0,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4.0,2.0,1.0,NaN,NaN,4500.0,3000.0,0.0,NaN,NaN,3750.0,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,16.0,3.0,2.0,NaN,NaN,6000.0,4000.0,0.0,NaN,NaN,5250.0,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1342.0,8190.0,88.0,999.0,NaN,NaN,25330000.0,350000.0,0.0,NaN,NaN,12666400.0,NaN,NaN

In [29]:
# Describe "Min_Yrs_Experience" column to see the unique values and their counts
df.describe()["Min_Yrs_Experience"].round(1)
# 99.9999% quantile of "Min_Yrs_Experience" is 20, so we can filter out the rows with "Min_Yrs_Experience" greater than 20
s = df["Min_Yrs_Experience"]
print("99.9999th Pct", f"${s.quantile(0.99999):,.0f}")

99.9999th Pct $61

In [25]:
# find the max and min values of the "Min_Yrs_Experience" column and all cresponding rows   
df[df["Min_Yrs_Experience"] == df["Min_Yrs_Experience"].max()]

,Employment_Types,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Position_Level,Company_Name,Salary_Max,Salary_Min,Status_ID,Job_Status,Job_Title,Avg_Salary,Category,Job_Group
664347,Full Time,2023-09-26,False,MCF-2023-0698710,2023-09-12,2023-09-12,0,0,1,88,3,Manager,NEW AMEERAH FOOD CHAINS PTE. LTD.,5000,3000,0,Open,STORE ASSISTANT,4000.0,Admin / Secretarial,Other
1767785,Internship/Attachment,2024-12-12,True,RANDOM_JOB_20251115011346015685_0,2024-01-16,2024-01-12,0,921,1604,88,579,Middle Management,BOND CAPITAL GROUP PTE. LTD.,6142101,107908,0,Closed,Senior Manager - Operations,3125004.5,Accounting / Auditing / Taxation,Other
1767786,Internship/Attachment,2024-12-12,True,RANDOM_JOB_20251115011346015685_0,2024-01-16,2024-01-12,0,921,1604,88,579,Middle Management,BOND CAPITAL GROUP PTE. LTD.,6142101,107908,0,Closed,Senior Manager - Operations,3125004.5,Admin / Secretarial,Other
1767787,Internship/Attachment,2024-12-12,True,RANDOM_JOB_20251115011346015685_0,2024-01-16,2024-01-12,0,921,1604,88,579,Middle Management,BOND CAPITAL GROUP PTE. LTD.,6142101,107908,0,Closed,Senior Manager - Operations,3125004.5,Building and Construction,Other

In [27]:
# save the cleaned data to a new CSV file
df.to_csv("../output3.csv", sep=";", index=False)

In [ ]:
# read the CSV file back into a dataframe, you can use the following code:
df_test_output = pd.read_csv("../data/output3.csv", sep=";", index_col=0)

In [11]:
# view the final dataframe and check the data types and count of non-null values
df_test_output.info()
df_test_output.describe(include="all").round(1)

NameError: name 'df_test_output' is not defined

In [ ]:
# Display the first 10 rows of the dataframe
df_test_output.head(10)

,Expiry_Date,Posted_On_Behalf,Job_Post_ID,New_Post_Date,Orig_Post_Date,Repost_Count,Total_Applications,Total_Views,Min_Yrs_Experience,Vacancies,Position_Level,Company_Name,Salary_Max,Salary_Min,Status_ID,Job_Status,Job_Title,Avg_Salary,Category
Employment_Types,,,,,,,,,,,,,,,,,,,
Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Environment / Health
Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Manufacturing
Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,1,Executive,WORKSTONE PTE. LTD.,2800,2000,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,Sciences / Laboratory / R&D
Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,2,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,Information Technology
Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,1,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,0,Closed,Senior Technician,4200.0,Repair and Maintenance
Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,1,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0,Information Technology
Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,3,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,0,Closed,Sales / Admin Cordinator,2900.0,Admin / Secretarial
Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,0,Closed,Software Support Engineer,5000.0,Consulting
Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,0,Closed,Software Support Engineer,5000.0,Information Technology
Full Time,2023-04-22,False,MCF-2023-0273974,2023-04-08,2023-04-08,0,4,110,1,3,Junior Executive,BYTECENTURE CONSULTING PTE. LTD.,6000,4000,0,Closed,Software Support Engineer,5000.0,Professional Services